### ISSUE TITLE
Library

### ISSUE THREAD

**Issue by kevinand11** [stranerd/sofa-web-frontend#2]
The recents section should show a list of the recently viewed courses or quizzes. There is an entity in interactions called views. Anytime you open the page for a course or quiz, you need to fire a call to create a view for the course or quiz

Then in the recents section, fetch the views sorted in descending order, and the entity associated with it

The saved section should show a list of all courses/quizzes that I have saved in my folders

- [x]  Create view anytime user opens a quiz or course page ✅
- [x]  Rework logic for fetching data for recents of both courses and quizzes ✅
- [x]  For purchased, remove the tabs at the top. Only courses can be bought, so no need to show quizzes tab ✅
- [x]  For the saved section, fetch all courses/quizzes I have saved in all my folders  ✅
- [x]  There is a bookmark icon on courses and quizzes, add that for all course and quiz cards outside library. Clicking on it should open up this modal https://www.figma.com/file/0I9k0lSag7dWUqPErBQKf0/SOFA?type=design&node-id=5724-37440&mode=design&t=X2cJSnHf8qeXqfMc-0, where I can save/unsave the item to one of my folders  ....  value passed in api is wrong the prop Id should contain the id of the current item being interacted with, not the previous list of values in the folder.saved ✅
- [x]  For quizzes and courses cards inside the library, remove the “Remove from library” cos it does nothing, and add a save/unsave option to bring up the same modal from the previous todo. Also add ‘add to course’ for quizzes that are not currently in a course.  ✅
- [x]  The link generated for share is /course/create and /quiz/create. These are the wrong links. They should be the links to the page to view the quiz or course ✅
- [x]  Report api documented in postman under interactions. Clicking on report should open a modal with a form to add a message. Similar for clicking on report for questions inside quiz  ✅
- [x]  Clicking on a course or quiz card show open the modal, and then whatever happens now is what should happen if I click on the start button in the modal. NB: remove show answers in quiz modal, for now. Every other section should be straightforward to implement(contact me if you stumble on any). For the similars section, there are new routes documented on postman for both courses and files
- [x]  Results and in progress tabs missing. They should both fetch a list of games and tests that I participated in, results would be status(ended or scored) while in progress would be other statuses ...... clicking on the card should take me to the game or test page, especially for in progress ones ❌ only in progress ones should take us back to the game page, since we dont have a results details page for now, ended plays should not click to anywhere
- [x] I click on a course I just created, and it takes me to the course page and shows me the “You have no access” empty state. I own the course so I always have access, so always grant me access ....doesnt work as expected.. I create a course and visit the course page, it shows the dont have access empty state.. As long as I am the creator of the course,  I have access, so you can check for the creator of the course... also there are other courses I can have access to even if I am not the creator, like courses created by an org I am in, or courses created by stranerd official account.. Lemme know when you are working on this, I will give you all the different conditions ❌ org must be actively subscribed before I can have access to their content
- [x] Send view for practice and flashcard quiz mode ✅
- [x] Send view for opening /course/:id and /quiz/:id page ✅
- [x] copy link to clipboard if navigator.share is not available .. link copied doesnt have the domain name, add the domain name, it just contains the path atm  ✅

**Comment by Doctordrayfocus** [comment]
_"also there are other courses I can have access to even if I am not the creator, like courses created by an org I am in, or courses created by stranerd official account.. Lemme know when you are working on this, I will give you all the different conditions"_

I believe a major business logic like this should be done from the backend. The course or quiz should contain a propery like "user_has_access", so the frontend just react to that. The logic and condition that affect this can change anytime.
