### ISSUE TITLE
File selectors missing in tutor verification page

### ISSUE THREAD

**Issue by kevinand11** [stranerd/sofa-web-frontend#73]
![P-IMG-20240119-WA0002](https://github.com/stranerd/sofa-web-frontend/assets/48160414/349679c8-a700-4e41-9799-7f6ef32afc00)
![P-IMG-20240119-WA0003](https://github.com/stranerd/sofa-web-frontend/assets/48160414/12f09d6e-ec17-403f-9068-6ee65c97d799)

Hot fix issue, so branch you create should start from prod not dev

**Comment by DevAdedeji** [comment]
What page is this?
Tried tutor verification and I wasn't redirected to this page

**Comment by DevAdedeji** [comment]
Seen, don't worry @kevinand11
